name: Unit Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies and project
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .

    - name: Run tests with pytest
      env:
        KMOE_USERNAME: ${{ secrets.KMOE_USERNAME }}
        KMOE_PASSWORD: ${{ secrets.KMOE_PASSWORD }}
      run: |
        pytest